markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Merissa Ramos
url: http://merissaramos.github.io
description: Merissa Ramos
linkedin_url: www.linkedin.com/in/MerissaRamos
